;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        anything-exit-minibuffer
        backward-delete-char
        cperl-electric-backspace
        cperl-electric-semi
        org-seq-home
        ruby-electric-close-matching-char
        ruby-electric-matching-char
        ruby-electric-quote
        sane-newline
        seq-end
        seq-home
        skeleton-pair-insert-maybe
        sp--self-insert-command
        ))

(setq mc/cmds-to-run-once
      '(
        anything-show-kill-ring
        org-self-insert-command
        ruby-electric-space
        sane-next-line
        sane-previous-line
        ))
